# Generated by Django 5.2.14 on 2026-05-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
